### ISSUE TITLE
JavaLoverRecipe example is outdated

### ISSUE THREAD

**Issue by archatas** [ulule/django-badgify#11]
The JavaLoverRecipe example in the README file is mixing up "JavaScript" and "Java" terms. I guess it should be removed or updated.

Here is it straight from the README:

    class JavaLoverRecipe(BaseRecipe):
        """
        People loving Java.
        """
        name = 'JS Lover'
        slug = 'js-lover'
        description = 'People loving JS programming language'

        @property
        def image(self):
            return staticfiles_storage.open('js-lover.png')

Other than that, django-badgify seems to be a very promising module ;)

**Comment by thoas** [comment]
thks, bad c/c
