### ISSUE TITLE
Please, add point "Add urls" to your Readme

### ISSUE THREAD

**Issue by Q-bart** [ulule/django-badgify#7]
There is not such poin in Readme. But urls are included in exaple project.

Thanks.

**Comment by gillesfabio** [comment]
@Q-bart Good point. We will add it in README. Thanks!

**Comment by gillesfabio** [comment]
@Q-bart Done (https://github.com/ulule/django-badgify/commit/a0d6b27ec6e60e3df3734a3c8a33064c2610286f). Thanks

**Comment by Q-bart** [comment]
Ok, thanks for awesome package
