### ISSUE TITLE
How can I run badgify_sync awards

### ISSUE THREAD

**Issue by Q-bart** [ulule/django-badgify#8]
Hello1

I want to make the code that will automatically track changes in db. For example, I want to award user, which posts have more than, for example 100 likes.

So I need to auto generating awards,
How can I do it?

**Comment by gillesfabio** [comment]
Hello @Q-bart,

Super easy. You don't need neither commands nor recipes.

* Create your badge instance (in admin or manually)
* Override Django `save()` or use signals to check the number of likes at save
* Create [award](https://github.com/ulule/django-badgify/blob/master/badgify/models/base/award.py#L13) instance 
* Done

**Comment by Q-bart** [comment]
Yep, thanks a lot

**Comment by gillesfabio** [comment]
You're welcome! Thanks for your interest.
