### ISSUE TITLE
Some desires

### ISSUE THREAD

**Issue by Q-bart** [ulule/django-badgify#9]
Hello!

This package is great! But I need some more functionality:

- How can I group Badges, that is, can you add the rating for Badges (for example, I want to display the best user's award in user's profile)?
- I can`t display the progress of competition some Award. So, can you add one more method to BadgeRecipe, in which we can define the method of getting progress?

Maybe, I don`t understand fully some code, so perhaps there are some solutions of these issues? 

Thank a lot!

**Comment by thoas** [comment]
Thank you for your interest but we are not here to work for you, sorry about that.

You are always welcome to send us pull requests if you want more features.
